config/routes.rb
Rails.application.routes.draw do
  root to:  'pages#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :users do
    get 'admins', to: 'admins#index'
  end

  namespace :pages do
    resources :searches, only: :index
  end

  resources :pages, except: :show
  # resources :pages, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :content, presence: true


  def self.search(search)
    return Page.all unless search
    Page.where('content LIKE(?)', "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
        #  :registerable,
        #  :recoverable, :rememberable, :validatable
        :trackable 
  enum role: { admin: "admin", user: "user" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def authenticate_admin!
    if user_signed_in? && current_user.admin?
      true
    else
      redirect_to root_path
    end
  end
end

app/controllers/pages/searches_controller.rb
class Pages::SearchesController < ApplicationController
  def index
    @pages = Page.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all.order("created_at DESC").page(params[:page]).per(30)
  end

  def new
    @page = Page.new
  end

  def create
    Page.create(page_params)
  end
  
  def destroy
    page = Page.find(params[:id])
    page.destroy
  end

  def edit
    @page = Page.find(params[:id])
  end
  
  def update
    page = Page.find(params[:id])
    page.update(page_params)
  end
  
  private
  def page_params
    params.require(:page).permit(:content)
  end
  
end

app/controllers/users/admins_controller.rb
class Users::AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @pages = Page.all.order("created_at DESC").page(params[:page]).per(24)
  end

  def new
    @page = Page.new
  end

  def create
    Page.create(page_params)
  end
  
  def destroy
    page = Page.find(params[:id])
    page.destroy
  end

  def edit
    @page = Page.find(params[:id])
  end
  
  def update
    page = Page.find(params[:id])
    page.update(page_params)
  end
  
  private
  def page_params
    params.require(:page).permit(:content)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && resource.admin?
      users_admins_path
    else
      root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/pages/searches_helper.rb
module Pages::SearchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yaritaikoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e9b41901ca.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    
  </head>
  <body>
    <%= render 'layouts/notifications' %>
    <header>
          <nav class="navbar">
                <a href="/pages" class="top">#PostYourWishes</a>
                <%= form_with(url: pages_searches_path, local: true, method: :get, class: "form-inline") do |form| %>
                  <%= form.text_field :keyword, placeholder: "検索", class: "form-control mr-sm-2 search-input" %>
                  <%= link_to pages_searches_path, class: "navbar__sh" do %>
                    <i class="fas fa-search"></i>
                  <% end %>
                <% end %>
          </nav>

    </header>

    <main>
     <%= yield %>
     <%# <p id="page-top"><a href="#wrap">TOP</a></p> %>
    </main>


    <footer class="footer">
      <div class="container">
        <%= link_to new_user_session_path, class:"sign" do %>
          <i class="fas fa-sign-in-alt"></i>
        <% end %>
        Copyright © #PostYourWishes 2020
        <%= link_to destroy_user_session_path, method: :delete, class:"sign" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    </footer>

  </body>
</html>

app/views/pages/create.html.erb
<div class="container successbox align-items-center">
  <div class="row successbox__msg">
    <div class="text-center">
      <p class="successbox__msg__text">
        Posted
      </p>
      <%= link_to '戻る', root_path, class:"btn btn-secondary sb-btn" %>
      <%= link_to 'やりたいこと', new_page_path, class:"btn btn-secondary sb-btn mt-5" %>
    </div>
  </div>
</div>

app/views/pages/destroy.html.erb
<div class="container successbox align-items-center">
  <div class="row successbox__msg">
    <div class="text-center">
      <h3 class="successbox__msg__text">
        Deleted
      </h3>
      <%= link_to '戻る', users_admins_path, class:"btn btn-secondary sb-btn" %>
    </div>
  </div>
</div>

app/views/pages/edit.html.erb
<div class="container-fluid d-flex align-items-center post">
  <div class="row post-box">
    <%= form_with(model: @page, local: true) do |form| %>
      <div class="post-box__title">
        編集する
      </div>
      <div class="post-box__text mx-auto text-center" >
        <%= form.text_area :content, placeholder: "", rows: "6" %>
        <%= form.submit "編集", class:"btn btn-secondary sb-btn" %>
        <%= link_to '戻る', users_admins_path, class:"btn btn-secondary sb-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
   <main>
      <header class="masthead">
        <div class="container d-flex align-items-center">
          <div class="masthead__content mx-auto text-center">
            <h2 class="mx-auto my-0 title">#アフターコロナで<br>やりたいことをポストしてね</h2>
            <h2 class="text-white-80 mx-auto title">#PostYourWishes</h2>
            <div class="start-btn">
              <%= link_to 'みる', root_path(anchor: "about"), class:"btn btn-secondary mcb" %>
              <%= link_to 'やりたいこと', new_page_path, class:"btn btn-secondary mcb mt-5" %>
            </div>
          </div>
        </div>
      </header>

      <div id="about" class="container-fluid view">
        <% @pages.each do |page| %>
          <div class="row view__box">
              <div class="view__box__content" >
              <%= simple_format(page.content) %>
              </div>
              <% if user_signed_in? %>
              <div class="view__box__btn">
                <div class="admbtn" >
                  <%= link_to '編集', "/pages/#{page.id}/edit", method: :get, class: "adm" %>
                </div>
                <div class="admbtn" >
                  <%= link_to '削除', "/pages/#{page.id}", method: :delete, class: "adm" %>
                </div>
              </div>
              <% end %>
          </div>
        <% end %>
        <%= paginate @pages, :params => { :anchor => 'about' } %>
      </div>
    </main>

app/views/pages/new.html.erb
<div class="container-fluid d-flex align-items-center post">
  <div class="row post-box">
    <%= form_with(model: @page, local: true) do |form| %>
      <div class="post-box__title">
        アフターコロナで <br>やりたいことは何ですか？
      </div>
      <div class="post-box__text mx-auto text-center" >
        <%= form.text_area :content, placeholder: "", rows: "6" %>
        <%= form.submit "ポスト", class:"btn btn-secondary sb-btn" %>
        <%= link_to '戻る', root_path, class:"btn btn-secondary sb-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/searches/index.html.erb
<div id="about" class="container-fluid view">
  <div class="search-hd">
    <%= link_to '戻る', root_path, class:"btn btn-outline-light my-2 my-sm-0" %>
  </div>
  <% @pages.each do |page| %>
    <div class="row view__box" id="sh" >
        <div class="view__box__content" >
        <%= simple_format(page.content) %>
        </div>
        <% if user_signed_in? %>
        <div class="view__box__btn">
          <div class="admbtn" >
            <%= link_to '編集', "/pages/#{page.id}/edit", method: :get, class: "adm" %>
          </div>
          <div class="admbtn" >
            <%= link_to '削除', "/pages/#{page.id}", method: :delete, class: "adm" %>
          </div>
        </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/pages/update.html.erb
<div class="container successbox align-items-center">
  <div class="row successbox__msg">
    <div class="text-center">
      <p class="successbox__msg__text">
        Updated
      </p>
      <%= link_to '戻る', users_admins_path, class:"btn btn-secondary sb-btn" %>
    </div>
  </div>
</div>

app/views/users/admins/index.html.erb
<div id="about" class="container-fluid view">
  <% @pages.each do |page| %>
    <div class="row view__box">
        <div class="view__box__content" >
        <%= simple_format(page.content) %>
        </div>
        <div class="view__box__btn">
          <div class="admbtn" >
            <%= link_to '編集', "/pages/#{page.id}/edit", method: :get, class: "adm" %>
          </div>
          <div class="admbtn" >
            <%= link_to '削除', "/pages/#{page.id}", method: :delete, class: "adm" %>
          </div>
        </div>
    </div>
  <% end %>
  <%= paginate @pages, :params => { :anchor => 'about' } %>
</div>

app/views/users/admins/searches/index.html.erb
<div id="about" class="container-fluid view">
  <div class="search-hd">
    <%= link_to '戻る', root_path, class:"btn btn-outline-light my-2 my-sm-0" %>
  </div>
  <% @pages.each do |page| %>
    <div class="row view__box">
        <div class="view__box__content" >
        <%= simple_format(page.content) %>
        </div>
        <div class="view__box__btn">
          <div class="admbtn" >
            <%= link_to '編集', "/pages/#{page.id}/edit", method: :get, class: "adm" %>
          </div>
          <div class="admbtn" >
            <%= link_to '削除', "/pages/#{page.id}", method: :delete, class: "adm" %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>